version: '3'
services:
  postgres:
    image: postgres:15
    container_name: cv-db
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    ports:
      - ${DB_PORT:-5444}:5432